// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"be-paymentordermanagement/app/controller"
	"be-paymentordermanagement/app/repository"
	"be-paymentordermanagement/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	paymentRepositoryImpl := repository.PaymentRepositoryInit(gormDB)
	paymentServiceImpl := service.PaymentServiceInit(paymentRepositoryImpl)
	paymentControllerImpl := controller.PaymentControllerInit(paymentServiceImpl)
	initialization := NewInitialization(paymentRepositoryImpl, paymentServiceImpl, paymentControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var paymentServiceSet = wire.NewSet(service.PaymentServiceInit, wire.Bind(new(service.PaymentService), new(*service.PaymentServiceImpl)))

var paymentRepoSet = wire.NewSet(repository.PaymentRepositoryInit, wire.Bind(new(repository.PaymentRepository), new(*repository.PaymentRepositoryImpl)))

var paymentCtrlSet = wire.NewSet(controller.PaymentControllerInit, wire.Bind(new(controller.PaymentController), new(*controller.PaymentControllerImpl)))
